<?php
/**
 * @var \App\View\AppView $this
 * @var iterable $appointments
 * @var string $month
 */
?>

<div class="view-container">
    <div class="page-header d-print-none">
        <h3 class="page-title">
            <i class="fas fa-chart-line"></i>
            Monthly Report: <?= h($month) ?>
        </h3>
        <div class="header-actions">
            <button onclick="window.print()" class="btn btn-outline-primary">
                <i class="fas fa-print"></i> Print Report
            </button>
            <?= $this->Html->link('<i class="fas fa-arrow-left"></i> Back', ['action' => 'index'], ['class' => 'btn btn-secondary', 'escape' => false]) ?>
        </div>
    </div>

    <div class="row mb-4 d-print-flex">
        <div class="col-md-4">
            <div class="stat-card primary p-3">
                <h3 class="mb-1"><?= count($appointments) ?></h3>
                <p class="text-muted mb-0">Total Appointments</p>
            </div>
        </div>
        </div>

    <div class="table-container bg-white rounded shadow-sm border">
        <?php if (empty($appointments)): ?>
            <div class="empty-state p-5">
                <i class="fas fa-calendar-times text-muted mb-3" style="font-size: 2rem;"></i>
                <p class="text-muted">No appointments found for this period.</p>
            </div>
        <?php else: ?>
            <div class="table-responsive">
                <table class="table custom-table table-striped mb-0">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Patient</th>
                            <th>Doctor</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($appointments as $appt): ?>
                        <tr>
                            <td class="fw-bold"><?= h($appt->appointment_date->format('M d, Y')) ?></td>
                            <td class="text-primary"><?= h($appt->appointment_time->format('H:i')) ?></td>
                            <td><?= h($appt->patient->name) ?></td>
                            <td>Dr. <?= h($appt->doctor->name) ?></td>
                            <td>
                                <span class="badge bg-secondary rounded-pill text-white px-3 py-1">
                                    <?= h($appt->status) ?>
                                </span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
    
    <div class="d-none d-print-block mt-4 text-center text-muted small">
        Generated by OmniCare on <?= date('Y-m-d H:i') ?>
    </div>
</div>