<?php
/**
 * @var \App\View\AppView $this
 * @var object $doctor
 * @var string $date
 * @var array $appointments
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>Daily Schedule - <?= h($date) ?></title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .info { margin-bottom: 20px; }
        .schedule-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .schedule-table th, .schedule-table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        .schedule-table th { background-color: #f8f9fa; font-weight: bold; }
        .no-appointments { text-align: center; padding: 40px; color: #666; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Schedule</h1>
        <h2><?= h($doctor->name ?? 'Doctor') ?></h2>
        <?php if (isset($doctor->department->name)): ?>
            <h3><?= h($doctor->department->name) ?> Department</h3>
        <?php endif; ?>
    </div>

    <div class="info">
        <p><strong>Date:</strong> <?= date('l, F j, Y', strtotime($date)) ?></p>
        <p><strong>Total Appointments:</strong> <?= count($appointments) ?></p>
        <p><strong>Generated:</strong> <?= date('Y-m-d H:i:s') ?></p>
    </div>

    <?php if (!empty($appointments)): ?>
        <table class="schedule-table">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Patient Name</th>
                    <th>Contact</th>
                    <th>Status</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($appointments as $appointment): ?>
                <tr>
                    <td><?= h($appointment->appointment_time->format('H:i')) ?></td>
                    <td><?= h($appointment->patient->name ?? 'N/A') ?></td>
                    <td><?= h($appointment->patient->contact_number ?? 'N/A') ?></td>
                    <td><?= h($appointment->status ?? 'Scheduled') ?></td>
                    <td><?= h($appointment->notes ?? '') ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="no-appointments">
            <h3>No appointments scheduled for this date</h3>
            <p>You have a free day!</p>
        </div>
    <?php endif; ?>

    <div class="footer">
        <p>Generated by OmniCare Hospital Management System</p>
        <p>Printed on: <?= date('Y-m-d H:i:s') ?></p>
    </div>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" class="btn btn-primary">Print Schedule</button>
        <button onclick="window.close()" class="btn btn-secondary">Close</button>
    </div>

    <script>
        // Auto-print when page loads (optional)
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>